# Automatically label PRs based on changed files
# Format for actions/labeler@v5

# Frontend related changes
'area: frontend':
  - changed-files:
    - any-glob-to-any-file: 'apps/frontend/**/*'

# Backend related changes
'area: backend':
  - changed-files:
    - any-glob-to-any-file: 'apps/server/**/*'

# Documentation changes
'documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

# Configuration changes
'config':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.config.js'
      - '**/*.config.ts'
      - '.github/**/*'

# Testing changes
'testing':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/specs/**/*'
      - 'jest.config.*'

# Dependencies
'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '**/package.json'

# DevOps and Infrastructure
'devops':
  - changed-files:
    - any-glob-to-any-file:
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - '.github/workflows/**/*'
      - '.dockerignore'

# Database and Seeders
'database':
  - changed-files:
    - any-glob-to-any-file:
      - '**/seeders/**/*'
      - '**/seed*.ts'
      - '**/seed*.js'

# UI/Styling
'ui/ux':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.css'
      - '**/*.scss'
      - '**/tailwind.config.*'
      - '**/postcss.config.*'

# TypeScript/Types
'typescript':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/tsconfig*.json'

# Shared/Library
'shared':
  - changed-files:
    - any-glob-to-any-file: 'libs/**/*'
