runtime: nodejs22
service: default

# Direct node execution for production
entrypoint: npm run start:backend:prod

instance_class: F2

env_variables:
  NODE_ENV: production
  # Secrets are injected via Cloud Build from Secret Manager
  # See cloudbuild-appengine.yaml

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always
