steps:
  # Install pnpm using corepack
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'corepack enable && corepack prepare pnpm@10.18.1 --activate'
    id: 'setup-pnpm'

  # Install dependencies
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'corepack enable && pnpm install --frozen-lockfile'
    waitFor: ['setup-pnpm']
    id: 'install'

  # Build shared library
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'corepack enable && pnpm build:shared'
    waitFor: ['install']
    id: 'build-shared'

  # Build server
  - name: 'node:22-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'corepack enable && pnpm build:backend'
    waitFor: ['build-shared']
    id: 'build-server'

  # Inject secrets into app.yaml and deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create app.yaml with secrets from environment variables
        cat > app.yaml <<EOF
        runtime: nodejs22
        service: default
        entrypoint: npm run start:backend:prod
        instance_class: F2
        env_variables:
          NODE_ENV: production
          MONGODB_URI: '$$MONGODB_URI'
          JWT_SECRET: '$$JWT_SECRET'
          RESEND_API_KEY: '$$RESEND_API_KEY'
          EMAIL_FROM: '$${EMAIL_FROM:-no-reply@shinobi-open-source.academy}'
          CORS_ORIGIN: '$${CORS_ORIGIN:-https://www.shinobi-open-source.academy/}'
          GITHUB_ORG_NAME: '$${GITHUB_ORG_NAME:-Shinobi-Open-Source-Academy}'
          ADMIN_EMAIL: '$${ADMIN_EMAIL:-contact@shinobi-open-source.academy}'
          ADMIN_PASSWORD: '$$ADMIN_PASSWORD'
          API_URL: '$${API_URL:-https://sos-academy-483918.uc.r.appspot.com/}'
          GITHUB_ORG_ADMIN_TOKEN: '$${GITHUB_ORG_ADMIN_TOKEN:-}'
        automatic_scaling:
          min_instances: 0
          max_instances: 2
          target_cpu_utilization: 0.65
        handlers:
          - url: /.*
            script: auto
            secure: always
        EOF

        # Deploy
        gcloud app deploy app.yaml --quiet --promote
    secretEnv: ['MONGODB_URI', 'JWT_SECRET', 'RESEND_API_KEY', 'ADMIN_PASSWORD']
    waitFor: ['build-server']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/mongodb-uri/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/resend-api-key/versions/latest
      env: 'RESEND_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/admin-password/versions/latest
      env: 'ADMIN_PASSWORD'

timeout: '1200s'
