# Cloud Build configuration for automatic deployment to Cloud Run
# Triggered on push to main branch

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sos-academy-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sos-academy-backend:latest'
      - '-f'
      - 'apps/server/Dockerfile'
      - '.'
    id: 'build-image'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sos-academy-backend:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sos-academy-backend:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sos-academy-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sos-academy-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# Substitution variables (can be overridden in Cloud Build trigger settings)
substitutions:
  _REGION: 'us-central1'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/sos-academy-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sos-academy-backend:latest'

# Build timeout (default is 10 minutes, increase for larger builds)
timeout: '1200s'
