blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Shinobi-Open-Source-Academy/sos-academy-platform/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 💭 Discord Community
    url: https://discord.gg/9Wgx7bCh
    about: Join our Discord for real-time chat and community support
  - name: 🔒 Security Issue
    url: https://github.com/Shinobi-Open-Source-Academy/sos-academy-platform/security/advisories/new
    about: Report a security vulnerability privately
