name: 📚 Documentation
description: Suggest improvements to documentation
title: "[DOCS] "
labels: ["documentation"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: What needs improvement?
      description: What's missing, unclear, or incorrect?
      placeholder: The docs for X are unclear because...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change (optional)
      description: How would you improve it?
      placeholder: I suggest...
