name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: What problem does it solve or what value does it add?
      placeholder: This would help because...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: Mockups, examples, or references
      placeholder: Add any other context here...
